var English = {
    "1. Introduction": "1. Introduction",
    "2. Version": "2. Version",
    "3. Seamless API": "3. Seamless API",
    "3.1 Introduction Seamless API": "3.1 Introduction Seamless API",
    "3.2 Workflow": "3.2 Workflow",
    "3.3 Setting": "3.3 Setting",
    "3.4 login request": "3.4 login request",
    "3.5 Call Back Service": "3.5 Call Back Service",
    "3.5.1 GetUserBalance": "3.5.1 GetUserBalance",
    "3.5.2 UserPlaceBet": "3.5.2 UserPlaceBet",
    "0. *": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*If you hold a master account, please create an agent API account under your master account and login with created agent API account before following this setting step.",
    "1.	Login": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. Login",
    "2.	Click": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. Click the Account menu and select the Profile menu",
    "3. Define": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3. Define the following API information",
    "3.1 Body": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This section is to illustrate the detail of implementing seamless in external partner system.",
    "3.2 Body": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Preliminary information in order to run the API, the partner system must have prevalence of commands So that the system can run the API under conditions.",
    "3.1 You can": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3.1 You can add multiple IP addresses by press the button",
    "3.2 You can": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3.2 You can click “API Document” button for preview Information",
    "3.3 You can": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3.3 You can click “Save Profile” button for saving data",
    "4. Transferwallet Api": "4. Transferwallet Api",
    "4.1 Introduction Transferwallet API": "4.1 Introduction Transferwallet API",
    "4.2 Workflow": "4.2 Workflow",
    "4.3 Setting": "4.3 Setting",
    "4.4 login request": "4.4 login request",
    "4.5 getUserBalance": "4.5 getUserBalance",
    "4.1 Body": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This section is to illustrate the detail of implementing transferwallet in external partner system.",
    "4.2 Body": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Preliminary information in order to run the API, the partner system must have prevalence of commands So that the system can run the API under conditions",
    "Request Body": "Request Body",
    "Example Request Body": "Example Request Body",
    "** Optional": "** Optional for direct/re-direct link.",
    "Version": "Version",
    "Description": "Description",
    "Modify date": "Modify date",
    "This interface will": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This interface will be called after the platform pays, and the member's bet will be returned to the third-party system in time. If the call times out or does not receive a response, the system will re-call every minute until it succeeds.",
    "You can add": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; You can add a value (BAC, DRA, SIC, ROU, MUL) to the parameter in the of the link (&game=) to redirect players to the specific games",
    "*Please keep": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *Please keep all of 'Call Back Service' <b style='color: red;'>confidentially</b>.<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Optional production security<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; You can also whitelist IP on the production environment. If need, please request our NAT IP to do whitelist.",
    "When a player": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; When a player enters the homepage or other pages, the Pretty Gaming system sends a request to obtain the amount of the actual player balance.",
    "When a player places": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; When a player places a bet, the Pretty Gaming system sends a request UserPlaceBet to the partner's system. The request will be timed out after 4 seconds and PlaceBetCancel will be sent.",
    "when previous PlaceBet": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; when previous PlaceBet is failed due to timeout or partner system error.Partner system should refund the user if the transaction has been done in the partner system side.If there are timeout or error, the request will be retried after n seconds within m tries.An expired request will move to the unsuccessful transaction list for back office to further process.Those unsuccessful transactions can be retry by the operator through the back office.",
    "Introduction Detail": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The API Service is used to access condition for working system including registration, query user accounts, user betting record query and game account balance transfer function.This document includes detail for access extend API service of system",
    "356": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; When a player places a bet, the Pretty Gaming system sends a request UserPayTips to the partner's system. The request will be timed out after 4 seconds and PlaceBetCancel will be sent.",
    "357": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; When a player places a bet, the Pretty Gaming system sends a request UserPayTipsCalcel to the partner's system. The request will be timed out after 4 seconds and PlaceBetCancel will be sent.",
    "Ratio": "Ratio",
    "Status": "Status",



    /////
    "4.3": "4.3 API",
    "Next": "Next",
    "Back": "Back",
    "Parameter": "Parameter",
    "Type": "Type",
    "Require": "Require",
    "7. Material": "8. Material",
    "1. Material": "1. Material",
    "Name": "Name",
    "Download": "Download",

};

var Chinese = {
    "1. Introduction": "1. 前言",
    "2. Version": "2. 版本",
    "3. Seamless API": "3. 单一钱包",
    "3.1 Introduction Seamless API": "3.1 Introduction Seamless API",
    "3.2 Workflow": "3.2 Workflow",
    "3.3 Setting": "3.3 设置",
    "3.4 login request": "3.4 请求登录",
    "3.5 Call Back Service": "3.5 返回服务",
    "3.5.1 GetUserBalance": "3.5.1 取得会员帐户馀额",
    "3.5.2 UserPlaceBet": "3.5.2 UserPlaceBet",
    "0. *": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*如果您现在是master account  请先在master account里  建立 Agent API account 然后 用Agent API account 登录login 接下来按照 setting step 设置",
    "1.	Login": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. 登录",
    "2.	Click": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. 单击“帐户”菜单，然后选择“个人资料”。",
    "3. Define": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3. 指定API连接信息。",
    "3.1 Body": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本文档介绍了如何与您系统连接 Seamless API。",
    "3.2 Body": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在以下情况下连接到 API 的基本信息：",
    "3.1 You can": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3.1 可以通过按下“添加 IP ”按钮指定多个 IP",
    "3.2 You can": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3.2 单击 “Click to API Document” 以转到所有API文档。",
    "3.3 You can": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3.3 单击 “Save Profile” 以保存设置。",
    "4. Transferwallet Api": "4.1 转账钱包 API",
    "4.1 Introduction Transferwallet API": "4.1 Introduction Transferwallet API",
    "4.2 Workflow": "4.2 Workflow",
    "4.3 Setting": "4.3 设置",
    "4.4 login request": "4.4 请求登录",
    "4.5 getUserBalance": "4.5 取得会员帐户馀额",
    "4.1 Body": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 本文档介绍了如何与您系统连接转账钱包 API",
    "4.2 Body": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 在以下情况下连接到API的基本信息：",
    "Request Body": "请求正文",
    "Example Request Body": "例子 请求正文",
    "** Optional": "** 连接选择",
    "Version": "版本",
    "Description": "具体内容",
    "Modify date": "修改日期",
    "This interface will": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 投注完成后，将激活此页面。 该请求将每分钟重新提交一次，直到成功为止。",
    "You can add": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 您可以增加（BAC，DRA，SIC，ROU，MUL）中的参数可将玩家直接带入游戏",
    "*Please keep": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *Please keep all of 'Call Back Service' <b style='color: red;'>confidentially</b>.<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Optional production security<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; You can also whitelist IP on the production environment. If need, please request our NAT IP to do whitelist.",
    "When a player": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 玩家进入主页或其他页面时 系统将要求玩家剩余的余额。",
    "When a player places": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 当玩家进行下注时，这个接口就会调用。如果在调用超过 4 秒后也没有回应，系统将会取消该投注并调用 PlaceBetCancel 让第三系统取消交易。",
    "when previous PlaceBet": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 当由于超时或系统问题而下注失败时 如果您的投注已记录在系统中，则系统必须退还客户。 如果系统时间不足或有问题 提交内容将重复发送，过期的请求将被提取并发送到后台不成功的 unsuccessful transaction list 列表中，以进行进一步处理，每个交易单 transaction 都可以在后台重复进行。",
    "Introduction Detail": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;API 这服务用于访问操作系统的条件，包括注册，查询用户帐户，用户投注记录查询和游戏帐户余额转移功能。 本文档包括系统访问扩展 API 服务的详细信息",
    "356": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; When a player places a bet, the Pretty Gaming system sends a request UserPayTips to the partner's system. The request will be timed out after 4 seconds and PlaceBetCancel will be sent.",
    "357": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; When a player places a bet, the Pretty Gaming system sends a request UserPayTipsCalcel to the partner's system. The request will be timed out after 4 seconds and PlaceBetCancel will be sent.",
    "Next": "Next",
    "Back": "Back",
    "Ratio": "Ratio",
    "Status": "Status",
    "7. Material": "8. Material",
    "1. Material": "1. Material",
    "Name": "Name",
    "Download": "Download",

};


var Thai = {   
};